service: shopping-list-api

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  memorySize: 256

  environment:
    TABLE_NAME: ${self:custom.shoppingListTableName}

  iamRoleStatements: ${file(./config/iamrolestatements.yml):iamRoleStatements}

package:
  exclude:
    - node_modules/**/*

plugins:
  - serverless-webpack

custom:
  shoppingListTableName: shopping-list-${self:provider.stage}
  tableReadThroughput: 5
  tableWriteThroughput: 1

functions: ${file(./config/functions.yml):functions}
resources:
  Resources:
    ${file(./config/dynamodb.yml)}


