ShoppingListTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ${self:custom.shoppingListTableName}
    AttributeDefinitions:
      - AttributeName: listId
        AttributeType: S
      # - AttributeName: itemId
        # AttributeType: S
    KeySchema:
      - AttributeName: listId
        KeyType: HASH
      # - AttributeName: itemId
        # KeyType: RANGE
    ProvisionedThroughput:
      ReadCapacityUnits: ${self:custom.tableReadThroughput}
      WriteCapacityUnits: ${self:custom.tableWriteThroughput}

